services:
  pritty_logger_development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pritty_logger_development
    stdin_open: true 
    tty: true
    volumes:
      - .:/app

  ruff_linter:
    build:
      context: .
      dockerfile: Dockerfile.ruff_linter
    volumes:
      - .:/app
    working_dir: /app
    command: ruff check --fix

  ruff_format:
    build:
      context: .
      dockerfile: Dockerfile.ruff_linter
    volumes:
      - .:/app
    working_dir: /app
    command: ruff format

  pritty_logger_tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: pritty_logger_tests